networks:
  app_network:

volumes:
  mysql_data:  
    driver: local
  composer_cache:
    driver: local

services:
  server:
    build:
      context: .
      dockerfile: docker/dockerfiles/nginx.dockerfile
    container_name: laravel_server
    ports:
      - 8080:80
    volumes:
      - ./backend:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - app_network

  php:
    build:
      context: .
      dockerfile: docker/dockerfiles/php.dockerfile
    container_name: APP
    volumes:
      - ./backend:/var/www/html:cached
      - composer_cache:/.composer
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - PHP_FPM_USER=laravel
      - PHP_FPM_GROUP=laravel
    networks:
      - app_network

  mysql:
    image: mysql:8.0.42
    container_name: DB
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root.pa55
      MYSQL_DATABASE: restaurant_app
      MYSQL_USER: user1
      MYSQL_PASSWORD: user1.pa55
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: laravel_phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8090:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root.pa55
    networks:
      - app_network